#!/usr/bin/env bash
set -u

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PACKAGE_SCRIPT="scripts/package_release.sh"
PHASE11_BRIDGE_SECURITY_SCRIPT="scripts/verify_phase11_bridge_security.sh"
PHASE11_MPV_BOUNDARY_SCRIPT="scripts/verify_phase11_mpv_boundary.sh"
PHASE13_PACKAGING_SCRIPT="scripts/verify_phase13_packaging.sh"
PHASE16_RELEASE_SCRIPT="scripts/verify_phase16_release.sh"
EXPORT_OPTIONS_PLIST="ReleasePackaging/ExportOptions.plist"
PLUGIN_MAIN_JS="IINAPlugin/GlanceHoldBridge.iinaplugin/main.js"
PLUGIN_PROTOCOL_TEST="IINAPlugin/GlanceHoldBridge.protocol.test.js"
XCODE_DERIVED_DATA="/private/tmp/GlanceHoldDerivedData-release-full"
XCODE_TEST_HOST_BUNDLE_ID="com.metatron.GlanceHold.ReleaseVerifierTestHost"
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
README_FILE="README.md"
README_ZH_FILE="README_zh.md"
PLUGIN_README_FILE="IINAPlugin/README.md"
RELEASE_PACKAGING_DOC="docs/release-packaging.md"
RELEASE_BODY_TEMPLATE="docs/release-body-template.md"

PUBLIC_CLAIM_FILES=(
  "$README_FILE"
  "$README_ZH_FILE"
  "$PLUGIN_README_FILE"
  "$RELEASE_PACKAGING_DOC"
  "$RELEASE_BODY_TEMPLATE"
)

ALLOWED_PLANNING_FILES=(
  ".planning/PROJECT.md"
  ".planning/ROADMAP.md"
  ".planning/MILESTONES.md"
  ".planning/RETROSPECTIVE.md"
  ".planning/STATE.md"
  ".planning/config.json"
)

failures=0
MODE=""
RELEASE_DIR=""
TARGET_REF=""
manifest_value=""
single_release_path=""

usage() {
  cat <<'USAGE'
Usage:
  scripts/verify_phase16_release.sh --source-gates
  scripts/verify_phase16_release.sh --release-gates --release-dir dist/releases/<release-id>
  scripts/verify_phase16_release.sh --publication-gates --target-ref <clean-publication-ref>

Options:
  --source-gates         Run full source verification before packaging.
  --release-gates        Verify a complete generated release artifact set.
  --release-dir <path>   Release directory generated by scripts/package_release.sh --verify.
  --publication-gates    Verify clean publication target tree hygiene.
  --target-ref <ref>     Clean publication branch or commit to inspect.
  --help, -h             Show this help.
USAGE
}

fail_usage() {
  printf 'error: %s\n' "$1" >&2
  usage >&2
  exit 64
}

set_mode() {
  local next_mode="$1"
  if [ -n "$MODE" ]; then
    fail_usage "exactly one mode is required"
  fi
  MODE="$next_mode"
}

require_value() {
  local option="$1"
  local value="${2:-}"
  if [ -z "$value" ]; then
    fail_usage "$option requires a value"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source-gates)
      set_mode "source"
      shift
      ;;
    --release-gates)
      set_mode "release"
      shift
      ;;
    --release-dir)
      require_value "$1" "${2:-}"
      RELEASE_DIR="$2"
      shift 2
      ;;
    --publication-gates)
      set_mode "publication"
      shift
      ;;
    --target-ref)
      require_value "$1" "${2:-}"
      TARGET_REF="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      fail_usage "unknown option: $1"
      ;;
  esac
done

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  failures=$((failures + 1))
}

pass() {
  printf 'PASS: %s\n' "$1"
}

require_file() {
  local path="$1"
  if [ -f "$path" ]; then
    pass "$path exists"
  else
    fail "$path is missing"
  fi
}

require_directory() {
  local path="$1"
  if [ -d "$path" ]; then
    pass "$path exists"
  else
    fail "$path is missing"
  fi
}

require_regular_file() {
  local path="$1"
  local description="$2"
  if [ -f "$path" ] && [ ! -L "$path" ]; then
    pass "$description"
  else
    fail "$description"
  fi
}

require_fixed_match() {
  local needle="$1"
  local path="$2"
  local description="$3"
  if grep -Fq -- "$needle" "$path"; then
    pass "$description"
  else
    fail "$description"
  fi
}

require_regex_absent() {
  local pattern="$1"
  local path="$2"
  local description="$3"
  local matches
  matches="$(grep -Eni -- "$pattern" "$path" || true)"
  if [ -n "$matches" ]; then
    printf 'Forbidden %s in %s:\n%s\n' "$description" "$path" "$matches" >&2
    fail "$description"
  else
    pass "$description"
  fi
}

require_command_pass() {
  local description="$1"
  shift
  if "$@"; then
    pass "$description"
  else
    fail "$description"
  fi
}

run_full_xctest_release_gate() {
  local xctestrun_matches=()
  local entitlements_matches=()
  local xctestrun_path
  local app_path
  local app_info_plist
  local entitlements_path

  xcodebuild build-for-testing \
    -project GlanceHold.xcodeproj \
    -scheme GlanceHold \
    -destination platform=macOS,arch=arm64 \
    -derivedDataPath "$XCODE_DERIVED_DATA" \
    -parallel-testing-enabled NO \
    -enableCodeCoverage NO || return 1

  shopt -s nullglob
  xctestrun_matches=("$XCODE_DERIVED_DATA"/Build/Products/*.xctestrun)
  entitlements_matches=("$XCODE_DERIVED_DATA"/Build/Intermediates.noindex/GlanceHold.build/Debug/GlanceHold.build/GlanceHold.app.xcent)
  shopt -u nullglob

  if [ "${#xctestrun_matches[@]}" -ne 1 ]; then
    printf 'Expected exactly one .xctestrun in %s/Build/Products, found %s\n' "$XCODE_DERIVED_DATA" "${#xctestrun_matches[@]}" >&2
    return 1
  fi
  xctestrun_path="${xctestrun_matches[0]}"

  app_path="$XCODE_DERIVED_DATA/Build/Products/Debug/GlanceHold.app"
  app_info_plist="$app_path/Contents/Info.plist"
  if [ ! -f "$app_info_plist" ]; then
    printf 'Expected built test host Info.plist at %s\n' "$app_info_plist" >&2
    return 1
  fi

  if [ "${#entitlements_matches[@]}" -ne 1 ]; then
    printf 'Expected exactly one test host entitlement file, found %s\n' "${#entitlements_matches[@]}" >&2
    return 1
  fi
  entitlements_path="${entitlements_matches[0]}"

  # The app must remain a menu-bar agent in production. For hosted CLI tests,
  # mutate only the temporary product so LaunchServices can launch and resume it.
  plutil -replace LSUIElement -bool NO "$app_info_plist" || return 1
  plutil -replace CFBundleIdentifier -string "$XCODE_TEST_HOST_BUNDLE_ID" "$app_info_plist" || return 1
  plutil -replace TestConfigurations.0.TestTargets.0.TestHostBundleIdentifier -string "$XCODE_TEST_HOST_BUNDLE_ID" "$xctestrun_path" || return 1
  plutil -replace TestConfigurations.0.TestTargets.0.BundleIdentifiersForCrashReportEmphasis.0 -string "$XCODE_TEST_HOST_BUNDLE_ID" "$xctestrun_path" || return 1
  plutil -replace TestConfigurations.0.TestTargets.0.ParallelizationEnabled -bool NO "$xctestrun_path" || return 1

  /usr/bin/codesign \
    --force \
    --sign - \
    --entitlements "$entitlements_path" \
    --timestamp=none \
    --generate-entitlement-der \
    "$app_path" || return 1

  "$LSREGISTER" -f -R -trusted "$app_path" || return 1
  /usr/bin/codesign --verify --deep --strict --verbose=2 "$app_path" || return 1

  xcodebuild test-without-building \
    -xctestrun "$xctestrun_path" \
    -destination platform=macOS,arch=arm64 \
    -derivedDataPath "$XCODE_DERIVED_DATA" \
    -parallel-testing-enabled NO \
    -enableCodeCoverage NO
}

extract_manifest_value() {
  local key="$1"
  local manifest_path="$2"
  local description="$3"
  manifest_value="$(plutil -extract "$key" raw "$manifest_path" 2>/dev/null || true)"
  if [ -n "$manifest_value" ]; then
    pass "$description"
  else
    fail "$description"
  fi
}

require_single_release_file() {
  local description="$1"
  local suffix="$2"
  local matches=()

  shopt -s nullglob
  case "$suffix" in
    dmg)
      matches=("$RELEASE_DIR"/*.dmg)
      ;;
    sha256)
      matches=("$RELEASE_DIR"/*.dmg.sha256)
      ;;
    manifest)
      matches=("$RELEASE_DIR"/*.manifest.json)
      ;;
    plugin)
      matches=("$RELEASE_DIR"/*.iinaplgz)
      ;;
  esac
  shopt -u nullglob

  single_release_path=""
  if [ "${#matches[@]}" -eq 1 ]; then
    single_release_path="${matches[0]}"
    pass "$description"
  else
    fail "$description"
  fi
}

run_source_gates() {
  require_file "$PACKAGE_SCRIPT"
  require_file "$PHASE11_BRIDGE_SECURITY_SCRIPT"
  require_file "$PHASE11_MPV_BOUNDARY_SCRIPT"
  require_file "$PHASE13_PACKAGING_SCRIPT"
  require_file "$PHASE16_RELEASE_SCRIPT"
  require_file "$EXPORT_OPTIONS_PLIST"
  require_file "$PLUGIN_MAIN_JS"
  require_file "$PLUGIN_PROTOCOL_TEST"

  require_command_pass "Full XCTest release gate passes" \
    run_full_xctest_release_gate
  require_command_pass "IINA plugin JavaScript syntax passes" \
    node --check IINAPlugin/GlanceHoldBridge.iinaplugin/main.js
  require_command_pass "IINA plugin protocol test passes" \
    node IINAPlugin/GlanceHoldBridge.protocol.test.js
  require_command_pass "package_release.sh Bash syntax passes" \
    bash -n scripts/package_release.sh
  require_command_pass "Phase 11 bridge security verifier Bash syntax passes" \
    bash -n scripts/verify_phase11_bridge_security.sh
  require_command_pass "Phase 11 MPV boundary verifier Bash syntax passes" \
    bash -n scripts/verify_phase11_mpv_boundary.sh
  require_command_pass "Phase 13 packaging verifier Bash syntax passes" \
    bash -n scripts/verify_phase13_packaging.sh
  require_command_pass "Phase 16 release verifier Bash syntax passes" \
    bash -n scripts/verify_phase16_release.sh
  require_command_pass "Phase 11 bridge security static gate passes" \
    bash scripts/verify_phase11_bridge_security.sh
  require_command_pass "Phase 11 MPV production boundary static gate passes" \
    bash scripts/verify_phase11_mpv_boundary.sh
  require_command_pass "Phase 13 packaging static gate passes" \
    bash scripts/verify_phase13_packaging.sh
  require_command_pass "ExportOptions.plist passes plutil lint" \
    plutil -lint ReleasePackaging/ExportOptions.plist
}

run_release_gates() {
  local release_basename
  local dmg_path
  local sha_path
  local manifest_path
  local plugin_path
  local release_id
  local manifest_dmg_file_name
  local manifest_sha_file_name
  local manifest_sha
  local checksum_sha
  local actual_sha
  local source_git_dirty
  local source_git_sha
  local plugin_expected_asset
  local plugin_version
  local plugin_bridge_protocol_version
  local plugin_listing

  if [ -z "$RELEASE_DIR" ]; then
    fail_usage "--release-gates requires --release-dir"
  fi

  require_directory "$RELEASE_DIR"
  release_basename="$(basename "$RELEASE_DIR")"

  require_single_release_file "release set contains exactly one real DMG" "dmg"
  dmg_path="$single_release_path"
  require_single_release_file "release set contains exactly one .dmg.sha256 file" "sha256"
  sha_path="$single_release_path"
  require_single_release_file "release set contains exactly one .manifest.json file" "manifest"
  manifest_path="$single_release_path"
  require_single_release_file "release set contains exactly one .iinaplgz plugin package" "plugin"
  plugin_path="$single_release_path"

  if [ -n "$dmg_path" ]; then
    require_regular_file "$dmg_path" "DMG is a regular file"
  fi
  if [ -n "$sha_path" ]; then
    require_regular_file "$sha_path" ".dmg.sha256 is a regular file"
  fi
  if [ -n "$manifest_path" ]; then
    require_regular_file "$manifest_path" ".manifest.json is a regular file"
  fi
  if [ -n "$plugin_path" ]; then
    require_regular_file "$plugin_path" ".iinaplgz is a regular file"
  fi

  if [ -z "$dmg_path" ] || [ -z "$sha_path" ] || [ -z "$manifest_path" ] || [ -z "$plugin_path" ]; then
    run_public_claim_gates
    return
  fi

  extract_manifest_value "releaseId" "$manifest_path" "manifest exposes releaseId"
  release_id="$manifest_value"
  if [ "$release_id" = "$release_basename" ]; then
    pass "manifest releaseId matches release directory basename"
  else
    fail "manifest releaseId matches release directory basename"
  fi

  extract_manifest_value "artifact.dmgFileName" "$manifest_path" "manifest exposes artifact.dmgFileName"
  manifest_dmg_file_name="$manifest_value"
  extract_manifest_value "artifact.sha256FileName" "$manifest_path" "manifest exposes artifact.sha256FileName"
  manifest_sha_file_name="$manifest_value"
  manifest_sha="$(plutil -extract artifact.sha256 raw "$manifest_path" 2>/dev/null || true)"
  if [[ "$manifest_sha" =~ ^[0-9A-Fa-f]{64}$ ]]; then
    pass "manifest exposes artifact.sha256"
  else
    fail "manifest exposes artifact.sha256"
  fi

  if [ "$manifest_dmg_file_name" = "$(basename "$dmg_path")" ]; then
    pass "manifest DMG filename matches sibling DMG"
  else
    fail "manifest DMG filename matches sibling DMG"
  fi

  if [ "$manifest_sha_file_name" = "$(basename "$sha_path")" ]; then
    pass "manifest checksum filename matches sibling .dmg.sha256"
  else
    fail "manifest checksum filename matches sibling .dmg.sha256"
  fi

  checksum_sha="$(awk '{ print $1; exit }' "$sha_path")"
  actual_sha="$(shasum -a 256 "$dmg_path" | awk '{ print $1; exit }')"
  if [ "$manifest_sha" = "$checksum_sha" ] && [ "$manifest_sha" = "$actual_sha" ]; then
    pass "artifact.sha256 matches .dmg.sha256 and shasum output"
  else
    fail "artifact.sha256 matches .dmg.sha256 and shasum output"
  fi

  require_command_pass "hdiutil verify passes for generated DMG" \
    hdiutil verify "$dmg_path"

  plugin_expected_asset="$(plutil -extract plugin.expectedAssetName raw "$manifest_path" 2>/dev/null || true)"
  if [ "$plugin_expected_asset" = "$(basename "$plugin_path")" ]; then
    pass "plugin.expectedAssetName matches sibling .iinaplgz"
  else
    fail "plugin.expectedAssetName matches sibling .iinaplgz"
  fi

  if [[ "$plugin_expected_asset" =~ ^GlanceHoldBridge-.+-build-.+\.iinaplgz$ ]]; then
    pass "plugin.expectedAssetName uses release plugin package pattern"
  else
    fail "plugin.expectedAssetName uses release plugin package pattern"
  fi

  plugin_listing="$(zipinfo -1 "$plugin_path" 2>/dev/null || true)"
  if printf '%s\n' "$plugin_listing" | grep -Eq '(^|/)Info\.json$'; then
    pass ".iinaplgz contains Info.json"
  else
    fail ".iinaplgz contains Info.json"
  fi

  if printf '%s\n' "$plugin_listing" | grep -Eq '(^|/)main\.js$'; then
    pass ".iinaplgz contains main.js"
  else
    fail ".iinaplgz contains main.js"
  fi

  source_git_dirty="$(plutil -extract source.gitDirty raw "$manifest_path" 2>/dev/null || true)"
  if [ "$source_git_dirty" = "false" ] || [ "$source_git_dirty" = "0" ]; then
    pass "source.gitDirty=false in manifest"
  else
    fail "source.gitDirty=false in manifest"
  fi

  source_git_sha="$(plutil -extract source.gitSha raw "$manifest_path" 2>/dev/null || true)"
  if [ -n "$source_git_sha" ] && git cat-file -e "$source_git_sha^{commit}" 2>/dev/null; then
    pass "source.gitSha exists as a local commit"
  else
    fail "source.gitSha exists as a local commit"
  fi

  plugin_version="$(plutil -extract plugin.version raw "$manifest_path" 2>/dev/null || true)"
  if [ -n "$plugin_version" ]; then
    pass "manifest exposes plugin.version"
  else
    fail "manifest exposes plugin.version"
  fi

  plugin_bridge_protocol_version="$(plutil -extract plugin.bridgeProtocolVersion raw "$manifest_path" 2>/dev/null || true)"
  if [[ "$plugin_bridge_protocol_version" =~ ^[0-9]+$ ]]; then
    pass "manifest exposes numeric plugin.bridgeProtocolVersion"
  else
    fail "manifest exposes numeric plugin.bridgeProtocolVersion"
  fi

  run_public_claim_gates
}

run_publication_gates() {
  local target_commit
  local tree_paths
  local path
  local allowed

  if [ -z "$TARGET_REF" ]; then
    fail_usage "--publication-gates requires --target-ref"
  fi

  case "$TARGET_REF" in
    dev|refs/heads/dev|local/*|refs/heads/local/*)
      fail "publication target ref must not be dev or local/*"
      ;;
    *)
      pass "publication target ref is not a local-only branch name"
      ;;
  esac

  target_commit="$(git rev-parse --verify "$TARGET_REF^{commit}" 2>/dev/null || true)"
  if [ -n "$target_commit" ]; then
    pass "git rev-parse --verify target ref resolves to a commit"
  else
    fail "git rev-parse --verify target ref resolves to a commit"
    return
  fi

  tree_paths="$(git ls-tree -r --name-only "$target_commit")"
  while IFS= read -r path; do
    [ -n "$path" ] || continue

    case "$path" in
      AGENTS.md)
        fail "publication target tree excludes AGENTS.md"
        ;;
      dist/*)
        fail "publication target tree excludes dist/ paths"
        ;;
      .planning/*)
        allowed=false
        for allowed_path in "${ALLOWED_PLANNING_FILES[@]}"; do
          if [ "$path" = "$allowed_path" ]; then
            allowed=true
            break
          fi
        done
        if [ "$allowed" = true ]; then
          :
        else
          fail "publication target tree excludes private .planning path: $path"
        fi
        ;;
    esac

    case "$path" in
      *.dmg|*.dmg.sha256|*.manifest.json|*.iinaplgz|*.xcarchive|*.zip|*.tar|*.tar.gz|*.tgz|*.pkg)
        fail "publication target tree excludes generated release artifact: $path"
        ;;
    esac
  done <<< "$tree_paths"

  if ! printf '%s\n' "$tree_paths" | grep -Fxq "AGENTS.md"; then
    pass "publication target tree excludes AGENTS.md"
  fi

  if ! printf '%s\n' "$tree_paths" | grep -Eq '^dist/'; then
    pass "publication target tree excludes dist/ paths"
  fi

  pass "git ls-tree -r --name-only inspected full publication target tree"
}

run_public_claim_gates() {
  local file

  for file in "${PUBLIC_CLAIM_FILES[@]}"; do
    require_file "$file"
    require_regex_absent 'signed and notarized' "$file" "signed and notarized overclaim"
    require_regex_absent 'Apple privacy review' "$file" "Apple privacy review overclaim"
    require_regex_absent 'no network communication' "$file" "no-network overclaim"
    require_regex_absent 'never uses network' "$file" "never-network overclaim"
    require_regex_absent 'supports[[:space:]]+VLC' "$file" "VLC support overclaim"
    require_regex_absent 'supports[[:space:]]+QuickTime' "$file" "QuickTime support overclaim"
    require_regex_absent 'supports[[:space:]]+browser video' "$file" "browser video support overclaim"
    require_regex_absent 'supports[[:space:]]+all players' "$file" "all-player support overclaim"
    require_regex_absent 'tracks your eyes' "$file" "eye-tracking overclaim"
    require_regex_absent 'knows where on the screen you are looking' "$file" "screen-gaze overclaim"
  done

  require_fixed_match "Camera frames are processed locally, not saved, and not uploaded." \
    "$README_FILE" "English README states local camera processing/not saved/not uploaded"
  require_fixed_match "local loopback bridge" \
    "$README_FILE" "English README discloses local loopback bridge"
  require_fixed_match "GlanceHold currently supports IINA." \
    "$README_FILE" "English README states IINA-only supported scope"
  require_fixed_match "Other players are not supported by the current release." \
    "$README_FILE" "English README states unsupported-player limits"
  require_fixed_match "Unsigned and not notarized; install requires macOS manual open / Open Anyway." \
    "$README_FILE" "English README states exact unsigned/manual-install sentence"
  require_fixed_match "Known limitations" \
    "$README_FILE" "English README has known limitations release-body field"

  require_fixed_match "摄像头画面会本地处理，不会保存，不会上传。" \
    "$README_ZH_FILE" "Chinese README states local camera processing/not saved/not uploaded"
  require_fixed_match "本地回环桥接" \
    "$README_ZH_FILE" "Chinese README discloses local loopback bridge"
  require_fixed_match "当前支持 IINA" \
    "$README_ZH_FILE" "Chinese README states IINA supported scope"
  require_fixed_match "当前 release 不支持其他播放器" \
    "$README_ZH_FILE" "Chinese README states unsupported-player limits"
  require_fixed_match "此版本未签名、未公证；安装需要通过 macOS 手动打开 / Open Anyway。" \
    "$README_ZH_FILE" "Chinese README states exact unsigned/manual-install meaning"
  require_fixed_match "已知限制" \
    "$README_ZH_FILE" "Chinese README has known limitations release-body field"

  require_fixed_match "local single-user loopback integration" \
    "$PLUGIN_README_FILE" "plugin README discloses local loopback trust boundary"
  require_fixed_match "The current GlanceHold app/plugin pair uses this no-token local loopback trust model." \
    "$PLUGIN_README_FILE" "plugin README states local loopback release trust model"
  require_fixed_match "Speed Control and Pause/Resume playback behavior are verified by the release verification workflow." \
    "$PLUGIN_README_FILE" "plugin README keeps playback behavior in release verification scope"

  require_fixed_match "Unsigned and not notarized; install requires macOS manual open / Open Anyway." \
    "$RELEASE_PACKAGING_DOC" "release packaging docs state exact unsigned/manual-install sentence"
  require_fixed_match "complete release set" \
    "$RELEASE_PACKAGING_DOC" "release packaging docs require complete release set"
  require_fixed_match "known limitations" \
    "$RELEASE_PACKAGING_DOC" "release packaging docs keep known limitations in public release facts"

  require_fixed_match "Camera frames are processed locally on the Mac and are not saved or uploaded by GlanceHold." \
    "$RELEASE_BODY_TEMPLATE" "release body template states local camera processing/not saved/not uploaded"
  require_fixed_match "local loopback communication" \
    "$RELEASE_BODY_TEMPLATE" "release body template discloses local loopback"
  require_fixed_match "Current verified playback target is IINA with the matching GlanceHold Bridge plugin." \
    "$RELEASE_BODY_TEMPLATE" "release body template states IINA-only verified scope"
  require_fixed_match "Other players are not supported by this release." \
    "$RELEASE_BODY_TEMPLATE" "release body template states unsupported-player limits"
  require_fixed_match "Unsigned and not notarized; install requires macOS manual open / Open Anyway." \
    "$RELEASE_BODY_TEMPLATE" "release body template states exact unsigned/manual-install sentence"
  require_fixed_match "Known Limitations" \
    "$RELEASE_BODY_TEMPLATE" "release body template has known limitations section"
}

case "$MODE" in
  source)
    if [ -n "$RELEASE_DIR" ] || [ -n "$TARGET_REF" ]; then
      fail_usage "--source-gates does not accept --release-dir or --target-ref"
    fi
    run_source_gates
    ;;
  release)
    if [ -n "$TARGET_REF" ]; then
      fail_usage "--release-gates does not accept --target-ref"
    fi
    run_release_gates
    ;;
  publication)
    if [ -n "$RELEASE_DIR" ]; then
      fail_usage "--publication-gates does not accept --release-dir"
    fi
    run_publication_gates
    ;;
  *)
    fail_usage "one mode is required"
    ;;
esac

if [ "$failures" -eq 0 ]; then
  printf 'PASS: Phase 16 release verifier completed\n'
  exit 0
fi

printf 'FAIL: Phase 16 release verifier found %d failure(s)\n' "$failures" >&2
exit 1
